version: "3"
services:  
  db:
    container_name: Crypto_database    
    image: postgres:14.3-alpine
    ports: 
      - "5432:5432"
    restart: always
    env_file: 
      - .env   
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}      
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      