version: "3"
services:  
  db:
    container_name: Crypto_database    
    image: postgres:14.3-alpine
    ports: 
      - "5432:5432"
    restart: always   
    environment:
      POSTGRES_PASSWORD: 1234      
      POSTGRES_USER: 'artem'
      POSTGRES_DB: 'crypto'
      